### ISSUE TITLE
virus at index.js line 11

### ISSUE THREAD

**Issue by DeWarexd** [Oztturk/ShareX-Custom-Uploader#1]
there is a infected typescript page in line 11. be careful while using.

**Comment by DeWarexd** [comment]
Uploading google-oauth2_101891748494932917868_tlk_7fZ_a5wgZk785khCiOLV1_1695588918589.mp4…

**Comment by Oztturk** [comment]
> there is a infected typescript page in line 11. be careful while using.

Line 11 is empty man
![image](https://github.com/Oztturk/ShareX-Custom-Uploader/assets/128193690/050f81fa-51be-4eb8-9dd0-bb625bf9363e)

**Comment by DeWarexd** [comment]
i mean 1 bro express is fake express its virus
![IMG_20230830_231640_664](https://github.com/Oztturk/ShareX-Custom-Uploader/assets/83973611/4e1663b4-b3ee-4751-a04f-ce0170c3dccd)

**Comment by Oztturk** [comment]
wow Its really incredible.
